name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  GCP_PROJECT: ${{ secrets.GCLOUD_PROJECT_ID }}
  GCR_HOSTNAME: us.gcr.io
  SERVICE_NAME: usermanager-service

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
    - name: Build and Push Image
      run: |-
        gcloud auth configure-docker us.gcr.io
        docker build -t us.gcr.io/ ${{ secrets.GCLOUD_PROJECT_ID }}/usermanager-service .
        docker push us.gcr.io/ ${{ secrets.GCLOUD_PROJECT_ID }}/usermanager-service
        
    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy usermanager-service \
          --image us.gcr.io/ ${{ secrets.GCLOUD_PROJECT_ID }}/usermanager-service \
          --region=us-central1
          --platform managed \
          --allow-unauthenticated
