name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Changez cela selon votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/ccm2023-nodeserver-20 .
        docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/ccm2023-nodeserver-20

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ccm2023-service-node \
          --image gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/ccm2023-nodeserver-20 \
          --port 62580 \
          --platform managed
